### ISSUE TITLE
Title should be "GORILLAS.BAS", not "GORILLA.BAS"

### ISSUE THREAD

**Issue by danielecapursi** [sblendorio/gorilla-cpm#1]
The original game was "GORILLAS.BAS", not "GORILLA.BAS".
How many gorillaS do you see in the game?

**Comment by danielecapursi** [comment]
I was wrong. Original file was "GORILLA.BAS", despite the game name was "QBasic GORILLAS".
It's Microsoft fault!

**Comment by sblendorio** [comment]
![DOS 5.0 diskset](http://www.sblendorio.eu/images/gorilla-name.png)
