### ISSUE TITLE
Error to compile gorilla-cpm 

### ISSUE THREAD

**Issue by plainspooky** [sblendorio/gorilla-cpm#2]
I've tried to compile Gorilla using Turbo Modula-2 and both in YAZE and MSX-DOS (by OpenMSX) I've received the same kind of error:
```
>C
Compile file: main           
Imported: XTerm
FROM XTerm IMPORT SEQ,ESCAPE,AskTermType,ResetTerm,
                  ^   Error in Identifier:
XTerm.SYM not found
```
So I've tried to compile XTerm first but it still didn't find XTERM.SYM.
```
>C
Workfile name: xterm
FROM Strings IMPORT CAPS,Length;
^   Error in Identifier:
XTERM.SYM not found
```
There is a specific sequence to compile it?

**Comment by sblendorio** [comment]
Hi, you have to compile (destination: disk and in PSEUDO CODE instead of
native) in this order:

XTERM.DEF
XTERM.MOD
GAME.DEF
GAME.MOD
MAIN.MOD

the last will end in MAIN.COM which is the executable file

Let me know.

Il sab 8 set 2018, 15:46 Giovanni Nunes <notifications@github.com> ha
scritto:

**Comment by sblendorio** [comment]
Hi, you have to compile (destination: disk and in PSEUDO CODE instead of
native) in this order:

```
XTERM.DEF
XTERM.MOD
GAME.DEF
GAME.MOD
MAIN.MOD
```

the last will end in MAIN which is the executable file. Last operation, LINK it to a SINGLE executable file.

Let me know.

**Comment by plainspooky** [comment]
Thanks!
